apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
  namespace: mysql-cluster
spec:
  replicas: 3
  secretName: mysql-root-password
  config:
    name: mysql-config
  volumeSpec:
    persistentVolumeClaim:
      storageClassName: "oci-bv"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
