apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.presslabs.com/cluster: mysql-cluster
  name: mysql-node-master
  namespace: mysql-cluster
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30306
  selector:
    v1alpha1.mysql.presslabs.com/cluster: mysql-cluster
    v1alpha1.mysql.presslabs.com/role: primary
  type: NodePort
