apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-cluster
  namespace: mysql-cluster
spec:
  members: 3
#  replicas: 3
#  rootPasswordSecret:
#    name: mysql-root-password
#  config:
#    name: mysql-config
#  nodeSelector:
#    app: mysql
#  volumeClaimTemplate:
#    metadata:
#      name: data
#    spec:
#      storageClassName: oci-bv
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 10Gi
