apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-cluster-with-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
